name: olx_clone
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  flutter_signin_button: ^2.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  legacy_progress_dialog: ^0.0.9
  cloud_firestore: ^2.0.0
  location: ^4.0.0
  geocoder: ^0.2.1
  google_sign_in: ^4.5.5
  email_validator: ^2.0.1
  open_mail_app: ^0.1.1
  csc_picker: ^0.2.5
  flutter_neumorphic: ^3.1.0
  cached_network_image: any
  provider: ^5.0.0
  image_picker: ^0.7.5+3
  firebase_storage: ^10.0.1
  galleryimage: any
  flutter_image_compress: ^1.0.0

#  flutter_facebook_auth: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
